name: Windows MinGW Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    name: MinGW | C++${{ matrix.cpp_std }}

    strategy:
      fail-fast: false
      matrix:
        cpp_std: [17, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSYS2 / MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja

      - name: Show compiler version
        shell: msys2 {0}
        run: |
          gcc --version
          g++ --version

      - name: Configure CMake (Debug)
        shell: msys2 {0}
        run: |
          cmake -B build-Debug -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_STANDARD=${{ matrix.cpp_std }} \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON

      - name: Build Project (Debug)
        shell: msys2 {0}
        run: cmake --build build-Debug --parallel

      - name: Run Tests (Debug)
        shell: msys2 {0}
        run: ctest --test-dir build-Debug --output-on-failure --parallel

      - name: Configure CMake (Release)
        shell: msys2 {0}
        run: |
          cmake -B build-Release -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_STANDARD=${{ matrix.cpp_std }} \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON

      - name: Build Project (Release)
        shell: msys2 {0}
        run: cmake --build build-Release --parallel

      - name: Run Tests (Release)
        shell: msys2 {0}
        run: ctest --test-dir build-Release --output-on-failure --parallel
